Repository WCSim/WCSim, pull requests merged in 2021-04, with the labels that each got.

#218 Resolve compiler warnings of deprecated header.
  CMakeLists.txt
  GNUmakefile_full
  include/WCSimDetectorConstruction.hh
  src/WCSimDetectorConstruction.cc
Labels: enhancement

#247 Fix for issue #245, support removal of digits in NDigits2 trigger.
  include/WCSimWCDigi.hh
  src/WCSimWCDigitizer.cc
  src/WCSimWCTrigger.cc
Labels: bug

#307 Update for cmake compilation with ROOT6 (+ scripts to compile on sukap)
  CMakeLists.txt
  GNUmakefile_full
  make.sh
  make_sukap.sh
  setup/SetupGitHub.sh
  setup/env_sukap.sh
Labels: bug

#292 Updated Radon model
  WCSim.mac
  include/RnModel_Fit_Params.hh
  include/WCSimGenerator_Radioactivity.hh
  src/WCSimGenerator_Radioactivity.cc
  src/WCSimPrimaryGeneratorMessenger.cc
Labels: Hyper-K
